### ISSUE TITLE
Error on 1.19 fabric

### ISSUE THREAD

**Issue by whyisghost** [RPMTW/RPMTW-Platform-Mod#217]
![image](https://user-images.githubusercontent.com/34228420/209328012-da99fb0f-b8e1-4215-8506-ad11baa0b0c6.png)

是直接使用RPMLauncher安裝的

1.5.3 跟 1.5.3+1 都會有上述圖片的問題

1.5.2 可以執行，但會crash並且無crash report
取消使用此Mod可以正常執行，而且這問題在其他版本跟模組包都有遇過 (例如: stoneblock 3)

請問這是有少安裝東西嗎??

**Comment by SiongSng** [comment]
請到 RPMTW 官方網站安裝正確的 RPMTW Platform Mod 版本
1.19 有分三個版本
這應該是 RPMLauncher 的 bug 未下載正確的模組版本

https://www.rpmtw.com/install/version
![image](https://user-images.githubusercontent.com/48402225/209357571-f38239fc-f4a4-4d22-b54a-25a803e123fc.png)

**Comment by whyisghost** [comment]
這邊

> 

這邊我也有嘗試過了，一樣會這樣

**Comment by SiongSng** [comment]
@whyisghost 那麻煩您截圖一下模組資料夾裡面放的模組

**Comment by whyisghost** [comment]
![image](https://user-images.githubusercontent.com/34228420/209456311-5126d0e5-e64e-4396-b3ce-9a0a351789e2.png)

**Comment by SiongSng** [comment]
@whyisghost 你 1.5.3+1 是用哪個檔案 截圖一下

**Comment by SiongSng** [comment]
![圖片](https://user-images.githubusercontent.com/48402225/209456907-3a0ce636-8011-47d4-aec5-2658bb64dd20.png)
沒事 我找到問題了 確實我有設定錯誤導致無法在 1.19 上執行

**Comment by SiongSng** [comment]
我稍後更新 感謝您的回報

**Comment by SiongSng** [comment]
現已修復 感謝您的回報

**Comment by whyisghost** [comment]
謝謝大大 XD

**Comment by SiongSng** [comment]
不客氣
